# IDS-----------------------------------------------------------------

# fonts
DEFAULT_FONT_TAG = "default"
TIMER_FONT_TAG = "timer font"

# themes
SETTINGS_THEME_ID = "settings theme"
DEFAULT_THEME_ID = "default theme"

# settings window
SETTINGS_WINDOW_ID = "Settings GUI"
SETTINGS_FOCUS_COMBO_ID = "Focus Timer Combo"
SETTINGS_SMALL_BREAK_COMBO_ID = "Small Break Combo"
SETTINGS_LONG_BREAK_COMBO_ID = "Long Break Combo"
SETTINGS_START_BUTTON_ID = "Start"

# pomodoro timer window
POMODORO_WINDOW_ID = "Pomodoro Timer"
POMODORO_FINISHED_WINDOW_ID = "Finished Window"
POMODORO_COUNTER_FIELD_ID = "Pomodoro Counter"
POMODORO_MIN_FIELD_ID = "Min"
POMODORO_SEC_FIELD_ID = "Second"
POMODORO_PAUSE_BTN_ID = "Pause"
POMODORO_STOP_BTN_ID = "Stop"
POMODORO_RESTART_BTN_ID = "Restart"
POMODORO_RESUME_BTN_ID = "Resume"
POMODORO_FOCUS_BTN_ID = "Focus btn"
POMODORO_SMALL_BREAK_BTN_ID = "Small Break"
POMODORO_LONG_BREAK_BTN_ID = "Long Break"

# VALUES--------------------------------------------------------------
VIEWPORT_HEIGHT = 700
VIEWPORT_WIDTH = 1000
SETTINGS_CONFIG_WINDOW_DIMENSIONS = [800, 300]
POMODORO_FINISHED_WINDOW_DIMENSIONS = [VIEWPORT_WIDTH / 2, VIEWPORT_HEIGHT / 2]
POMODORO_DISPLAY_TEXT_DIMENSION = [200, 200]
POMODORO_FINISHED_WINDOW_POS = [VIEWPORT_WIDTH - POMODORO_FINISHED_WINDOW_DIMENSIONS[0]/2,
                                VIEWPORT_HEIGHT - POMODORO_FINISHED_WINDOW_DIMENSIONS[1]/2]
POMODORO_COUNTER_FIELD_WIDTH = 550

DEFAULT_FONT_PATH = "resources/fonts/Simpleton-Gothic.ttf"
TIMER_FONT_PATH = "resources/fonts/Simpleton-Gothic.ttf"
BANNER_IMG_PATH = "resources/images/tomato-banner.png"
SOUND_PATH = "resources/sounds/bell.mp3"
STUDYING_IMAGE_PATH = "resources/images/studying.png"
FINISHED_IMAGE_PATH = "resources/images/finished.png"

# main
VIEWPORT_TITLE = "Pomodoro Timer"
DPG_FONT_SCALE = 1.25

# settings window
SETTINGS_COMBO_WIDTH = 400
SETTINGS_COMBO_HEIGHT_PADDING = 15
SETTINGS_FOCUS_COMBO_DEFAULT_VALUE = 25
SETTINGS_SMALL_BREAK_COMBO_DEFAULT_VALUE = 2
SETTINGS_LONG_BREAK_COMBO_DEFAULT_VALUE = 15
SETTINGS_BANNER_HEIGHT_SPACER = 20
SETTINGS_BANNER_WIDTH_SPACER = 30
SETTINGS_COMBOS_HEIGHT_SPACER = 25
SETTINGS_COMBOS_WIDTH_SPACER = 275
SETTINGS_START_BTN_WIDTH_SPACER = 100
SETTINGS_START_BUTTON_LABEL = "Start Pomodoro"
SETTINGS_START_BUTTON_HEIGHT = 100
SETTINGS_START_BUTTON_WIDTH = 200
SETTINGS_FOCUS_COMBO_TOOLTIP = "Number of mins to stay focused"
SETTINGS_SMALL_BREAK_COMBO_TOOLTIP = "Number of mins for a small break"
SETTINGS_LONG_BREAK_COMBO_TOOLTIP = "Number of mins for a long break"
SETTINGS_START_BTN_TOOLTIP = "Start Pomodoro Session"

# pomodoro timer window
POMODORO_MIN_FIELD_LABEL = "min"
POMODORO_SEC_FIELD_LABEL = "sec"
POMODORO_COUNTER_FIELD_LABEL = "Pomodoros"
POMODORO_FOCUS_BTN_LABEL = "Focus Time"
POMODORO_SMALL_BREAK_BTN_LABEL = "Small Break"
POMODORO_LONG_BREAK_BTN_LABEL = "Long Break"